#!/bin/bash

# permissions
echo "Fixing /config permissions. . ."
chown -R epguser:epguser \
  /config

# chown the app directory, but not node_modules
echo "Fixing app permissions. . ."
find /app/epg -maxdepth 1 ! -name node_modules ! -name epg -exec chown -R epguser:epguser '{}' \;

cd /app/epg || exit

exec \
  s6-setuidgid epguser npm run serve
